SRC = readLista.c readConference.c readJournal.c LLArtigos.c AVLArtigos.c  trataValidas.c main.c
CCFLAGS = -O3 -Wall -Wextra
CCC = gcc
FILE = PARSER_LI3

$(FILE): $(SRC:.c=.o)
	$(CCC) -o $(FILE) $(CCFLAGS) $(SRC)
